// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-1]
	_ = x[J-11]
	_ = x[Q-12]
	_ = x[K-13]
}

const (
	_Rank_name_0 = "A"
	_Rank_name_1 = "JQK"
)

var (
	_Rank_index_1 = [...]uint8{0, 1, 2, 3}
)

func (i Rank) String() string {
	switch {
	case i == 1:
		return _Rank_name_0
	case 11 <= i && i <= 13:
		i -= 11
		return _Rank_name_1[_Rank_index_1[i]:_Rank_index_1[i+1]]
	default:
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
